name: github pages

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 部署到elementui_echarts_vue2的gh-pages分支上
          # 参考资料 => https://milkmidi.medium.com/%E6%B7%B1%E5%85%A5%E4%BD%86%E4%B8%8D%E6%B7%BA%E5%87%BA-%E5%A6%82%E4%BD%95%E7%94%A8-github-actions-%E8%87%AA%E5%8B%95%E7%99%BC%E4%BD%88-gh-pages-8183464dfe84
          github_token: ${{ secrets.GITHUB_TOKEN }} # 手工生成一对公钥私钥
          # external_repository: FionaYuliang/elementui_echarts_vue2
          publish_branch: gh-pages
          publish_dir: ./public

          